name = "DifferentialGeometry"
uuid = "5475bf12-675d-4abb-a0fd-3970e2ffd1d9"
authors = ["bernd.h.mehnert <bernd.h.mehnert@gmail.com>"]
version = "0.1.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
